import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header(){
  return(
    <nav className="flex justify-between items-center px-10 py-5 border-b-2 bg-[#B0DB9C]">
      <div className="text-xl font-bold ml-20">
        <h2>Stephen Akrong</h2>
      </div>
      <div className="flex flex-row space-x-15">
        <a href="#about">About</a>
        <a href="#skills">Skills</a>
        <a href="#projects">Projects</a>
        <a href="#contact">Contact Me</a>
      </div>
    </nav>
  )
}

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang='en'>
      <body className="bg-green-200 text-gray-900 font-sans">
        <Header />
        {children}
      </body>
    </html>
  );
}
